### ISSUE TITLE
TypeError: Python3 requires f_handle to be in 'wb' or 'ab' mode

### ISSUE THREAD

**Issue by FilomenoSanchez** [rigdenlab/conkit#100]
## General Information

- ConKit version: commit https://github.com/rigdenlab/conkit/commit/06a94befb6b099e34b0d23f81e2260f4d1fadf5b
- Python version: 3.9

## Example
Trying to convert any file format into`ccmpred` breaks the code. 

```
conkit-convert seq.npz rosettanpz seq.ccmpred ccmpred
```

## Traceback

```
Traceback (most recent call last):
  File "/home/filo/.local/lib/python3.9/site-packages/conkit/command_line/conkit_convert.py", line 87, in <module>
    main()
  File "/home/filo/.local/lib/python3.9/site-packages/conkit/command_line/conkit_convert.py", line 77, in main
    conkit.io.convert(args.infile, args.informat, args.outfile, args.outformat)
  File "/home/filo/.local/lib/python3.9/site-packages/conkit/io/__init__.py", line 94, in convert
    write(fname_out, format_out, hierarchy)
  File "/home/filo/.local/lib/python3.9/site-packages/conkit/io/__init__.py", line 187, in write
    parser_out.write(f_out, hierarchy, **kwargs)
  File "/home/filo/.local/lib/python3.9/site-packages/conkit/io/ccmpred.py", line 129, in write
    raise TypeError("Python3 requires f_handle to be in 'wb' or 'ab' mode")
TypeError: Python3 requires f_handle to be in 'wb' or 'ab' mode
```

**Comment by sadiogo** [comment]
I was thinking about this code and it might actually be quite simple.

1. You need to parse the MSA and create a list with every sequence. 

2. find all gap positions in first sequence, store their index in another list (gap_positions) and delete them in the original sequence.

3. In all other sequences, run a for loop and inquire if the ```position in gap_positions``` is a gap also, if yes, delete it. If not, convert the letter  to lower case.

That's it. That's how the original a3m file should look like. However, many programs don't use the lowercase letters, so they erroneously ask for an a3m file, but without the insertions from other non-query sequences. In that case, conkit-convert could also have the option to remove insertions, in which case you just delete every gap position in the gap_positions list, for every sequence, regardless of they harbor a gap or an amino acid.
