### ISSUE TITLE
Conkit-precision should be able to compare two contact maps if a contact map is provided instead of a PDB file. 

### ISSUE THREAD

**Issue by sadiogo** [rigdenlab/conkit#101]
I have a suggestion. Conkit-precision converts a PDB into a contact map so it can be compared to another contact map. But when you try to compare two contact maps, it returns a traceback saying ```AttributeError: 'ContactMap' object has no attribute 'as_contactmap'```. Since it is already capable of comparing two contact maps, the code can be modified to skip pdb2contactmap conversion in case you've already input two contact maps.

To get it working, I modified the code grotesquely with a simple try-except in line 87:
```
try:
        pdb = pdb.as_contactmap()
except:
        print('PDB file conversion into contact map failed. Will try to compare two contact maps instead.')
```

it worked for casprr contact maps but failed between two caspmode2 maps:
```
Traceback (most recent call last):
  File "/home/sadiogo/.local/lib/python3.6/site-packages/conkit/command_line/conkit_precision.py", line 117, in <module>
    main()
  File "/home/sadiogo/.local/lib/python3.6/site-packages/conkit/command_line/conkit_precision.py", line 106, in main
    con_matched = con_sliced.match(pdb)
  File "/home/sadiogo/.local/lib/python3.6/site-packages/conkit/core/contactmap.py", line 810, in match
    raise ValueError(msg + contact_map2.id)
ValueError: Error creating reliable keymap matching the sequence in ContactMap: map_1
````

I tried debugging by comparing the same contact map (capmode2 format) in both positions. I noticed two things:

1. The ```altloc=true``` in line 804 makes the length of contact_map2_keymap = 1; if you remove it, the  you get the correct keymapping. 

2. The ```encoded_repr[1]``` is always the same, no matter which contact map you use. It's a big vector filled with 45 (which is the encoding for gaps). It seems this is the problem. The ```contact_map2_repr_sequence.seq_ascii``` is always a string full of gaps.

Specifically, in line 780-781 everything is fine, both contact maps are assigned the correct sequences in the variables ```contact_map1_full_sequence, contact_map2_full_sequence```. But then in the next block of the code:

```
contact_map2_repr_sequence = contact_map2_full_sequence.align_local(
            contact_map2.repr_sequence_altloc, **config
```

```contact_map2_repr_sequence ``` is assigned a bunch of gaps and that's where the code makes no sense. It appears the ```repr_sequence_altloc``` property is not working correctly for ```contac_map2```. I tried using just ```repr_sequence``` instead of ```repr_sequence_altloc```, but no luck.

Then I got it "fixed" by using ```repr_sequence``` instead of ```repr_sequence_altloc``` in line 788 **AND** removing ```altloc=true``` in line 804. But something is not working right, because I compared identical maps and the precision score was ```Precision score: 0.435933``` instead of the expected ```1.0```. I checked and ```contact_map2_repr_sequence ``` is still being assigned a bunch of gaps.

So it's a problem when calling the ```_construct_repr_sequence``` function, which is where gaps get assigned to the representative sequence. That's as far as my debugging goes lol.

I've attached the two caspmode2 maps I want to compare, although I've been using just one to debug.

-------------------------------------//-------------------------------------

I gave up one trying to compare them as caspmode2 files, so I converted them to casprr using conkit_convert and reran conkit_precision. That seemed to work, but the precision score was ```1.0```.

This isn't correct, as can be seen in the superposition of both maps (using the converted casprr format) using conplot. You can see grey and red spots, so there is clearly differences that should have been detected by conkit_precision.
![comparison](https://user-images.githubusercontent.com/68039828/151647733-cee1b103-58e8-4faa-904a-92974662825d.png)

The strange thing is this: if I compare these contact maps individually against another reference map, they give different precisions, indicating they are different. So how come they yield precision 1.0 when compared to each other? 

God, I just wish science was less of a hardship; all I want is to finish running some analyses so I can finish my dissertation and submit the paper lol

 

[HiSSA-raptor-results.txt](https://github.com/rigdenlab/conkit/files/7962783/HiSSA-raptor-results.txt)
[MAFFT-raptor-results.txt](https://github.com/rigdenlab/conkit/files/7962784/MAFFT-raptor-results.txt)

**Comment by sadiogo** [comment]
I'm really hoping you can figure this one out @FilomenoSanchez. How can the plot indicate differences and the precision be equal to 1.0?

**Comment by sadiogo** [comment]
Naturally, the order in which the contact maps are compared matters. I've tested this with other maps and some times a precision of 1.0 becomes 0.9 when you change the order, which makes sense. But in this case I've tried both orders, and both result in 1.0 precision. In fact, none of the comparison should result in 1.0, as there are red AND grey spots in the plot. If we could discern only one of those colors, then one of the comparisons might result in 1.0 precision and the other not. But this is not the case.

**Comment by sadiogo** [comment]
Okay, so I had a crazy idea and it seemed to really work this time. 

```conkit_plot peval``` has to calculate precision over a range of L cutoffs, so I took a look at the code and, unsurprisingly, it was almost identical to the code in conkit_precision. So I made it identical and voilá, it worked. Here's the new code starting on line 75 in the ```conkit_precision``` script:
```
    global logger
    logger = conkit.command_line.setup_logging(level="info")

    # >>> Code from conkit_plot peval >>
    seq = conkit.io.read(args.seqfile, args.seqformat)[0]
    con = conkit.io.read(args.confile, args.conformat)[0]
    if args.conformat in DISTANCE_FILE_PARSERS:
        con = con.as_contactmap()
    # <<< code from conkit_plot peval <<<
   
    # con = conkit.io.read(args.confile, args.conformat)[0] # original line
    con.sequence = seq
    con.set_sequence_register()

    if args.pdbchain:
        pdb = conkit.io.read(args.pdbfile, args.pdbformat)[args.pdbchain]
    else:
        pdb = conkit.io.read(args.pdbfile, args.pdbformat)[0]

    pdb.sequence = seq
    pdb.set_sequence_register()
    
    # added this to compare two contact maps
    try:
        pdb = pdb.as_contactmap()
    except:
        print('PDB file conversion into contact map failed. Will try to compare two contact maps instead.')

    logger.info("Min sequence separation for contacting residues: %d", args.dtn)
    logger.info("Contact list cutoff factor: %f * L", args.dfactor)

    con.remove_neighbors(min_distance=args.dtn, inplace=True)
    # ncontacts = int(seq.seq_len * args.dfactor) # original line
    con.sort("raw_score", reverse=True, inplace=True)
    # con_sliced = con[:ncontacts] # original line

    # con_matched = con_sliced.match(pdb) # original line
    con_matched = con.match(pdb, renumber=True, remove_unmatched=True) # line from conkit_plot peval
    precision = con_matched.precision
```
I commented the original lines.

I also had to add ```from conkit.io import DISTANCE_FILE_PARSERS``` at the beginning of the script. The good part is that this also enabled ```conkit_precision``` to compare two PDB files, which was already possible in ```conkit_plot peval```.

I also added the try-except block in ```conkit_plot peval" to enable comparison between two contact maps, which it wasn't able to do. Also worked.

Please let me know if I messed it all up.

**Comment by FilomenoSanchez** [comment]
Hi @sadiogo. To calculate precision, `conkit.plot peval` and `conkit.precision` assume that the reference you are providing is a PDB file (otherwise it doesn't make much sense to talk about precision). Since PDB files might have missing residues, there are a series of transformations that need to be made for the comparison to make sense. If you want to provide something different than a PDB, the current implementation won't work. I would suggest the following:

1. The quickest way for this to work with CASP-MODE-2 files is making the following changes:
```diff
--- a/conkit/command_line/conkit_precision.py
+++ b/conkit/command_line/conkit_precision.py
@@ -81,15 +81,20 @@ def main():
         pdb = conkit.io.read(args.pdbfile, args.pdbformat)[0]
 
     seq = conkit.io.read(args.seqfile, args.seqformat)[0]
-
     pdb.sequence = seq
     pdb.set_sequence_register()
-    pdb = pdb.as_contactmap()
+
+    if args.pdbformat in conkit.io.DISTANCE_FILE_PARSERS:
+        pdb = pdb.as_contactmap()
 
     con = conkit.io.read(args.confile, args.conformat)[0]
     con.sequence = seq
     con.set_sequence_register()
 
+    if args.conformat in conkit.io.DISTANCE_FILE_PARSERS:
+        con = con.as_contactmap()
+
+
     logger.info("Min sequence separation for contacting residues: %d", args.dtn)
     logger.info("Contact list cutoff factor: %f * L", args.dfactor)
```
```diff
diff --git a/conkit/io/caspmode2.py b/conkit/io/caspmode2.py
index 72d37be..f5d50d2 100644
--- a/conkit/io/caspmode2.py
+++ b/conkit/io/caspmode2.py
@@ -74,6 +74,8 @@ class CaspMode2Parser(DistanceFileParser):
             raw_score = float(line[2])
             distance_scores = tuple([float(p) for p in line[3:]])
             _distance = Distance(res1_seq, res2_seq, distance_scores, DISTANCE_BINS, raw_score=raw_score)
+            _distance.res1_altseq = res1_seq
+            _distance._res2_altseq = res2_seq
             _map.add(_distance)
 
         return hierarchy
```
After these changes I get `Precision score: 0.890323`

2.  The alternative is to calculate the TP and FP yourself. You can do this using the following snippet (assume `cmap_1` is the reference):
```python
import conkit.io

cmap_1 = conkit.io.read("MAFFT-raptor-results.txt", "caspmode2")
cmap_1.as_contactmap()
cmap_2 = conkit.io.read("HiSSA-raptor-results.txt", "caspmode2")
cmap_2.as_contactmap()

cmap_1_set = {c.id for c in cmap_1}
cmap_2_set = {c for c in cmap_2}

TP = len(cmap_1_set & cmap_2_set)
FP = len(cmap_2_set - cmap_1_set)

precision = TP / (TP+FP)

```

But again, I'm not sure if you can really talk about "precision" here as both files are predictions... Also, in the future if you want to show code changes I would suggest using `diff` notation, otherwise it's quite difficult to follow what's going on.

**Comment by sadiogo** [comment]
Hi @FilomenoSanchez, sorry for the complicated way I showed code changes. I will try to diff notation from now on.

I kept the changes I had made and changed just the caspmode2.py file to see if I would get the same results as you did. It worked, which means I didn't mess up the calculations.

Then I backed up my changes and implemented your changes to the conkit_precision script. It fixed the ```AttributeError: 'ContactMap' object has no attribute 'as_contactmap'``` error when I try to compare two casprr contact maps, but the calculations wen back to being wrong. To try it yourself, just convert those two caspmode2 maps into casprr and run conkit_precision on them. You will get ```precision score = 1.0```. This is obviously wrong because of the plot I posted in my comments above. You can see red and grey spots, which indicate there are differences in both maps. Notwithstanding, when you run ```conkit_plot peval``` on those maps (you'll have to bypass the ```AttributeError```) they clearly show precision isn't ```1.0``. When I was running the ```conkit_precision``` script with my modifications, I was getting ```0.854126``` or ```0.889756``` (depending on which map was reference), which is what I was seeing in the ```conkit_plot peval``` output plot.

I think it has to do with this block of code on line 101 of the ```conkit_precision``` script:

```
con.remove_neighbors(min_distance=args.dtn, inplace=True)
ncontacts = int(seq.seq_len * args.dfactor)
con.sort("raw_score", reverse=True, inplace=True)
con_sliced = con[:ncontacts]

con_matched = con_sliced.match(pdb) 
precision = con_matched.precision
```
In the ```conkit_plot peval``` function, this calculated like this:
```
con.remove_neighbors(min_distance=args.dtn, inplace=True)
con.sort("raw_score", reverse=True, inplace=True)

con_matched = con.match(pdb, renumber=True, remove_unmatched=True)
precision = con_matched.precision
```
If you mirror the ```conkit_plot``` code in ```conkit_precison```, you will get the ```0.854126``` or ```0.889756``` values, which make more sense.  

But would it be normal for the value to be one thing in casprr format and another in caspmode2?

And yes, you are right, we are not talking about "precision" anymore, it's just a measure of similarity between the contact maps. But that is what I was looking for.

**Comment by sadiogo** [comment]
I see...let me see if I can make it clearer.

In your latest commit, if you calculate the precision of the two maps (casprr format), you get precision =1.0.
However, if you generate a plot of these maps in conplot, you will see they are different.

Also in you latest commit, if you change lines 101-107, which should display: 
```
con.remove_neighbors(min_distance=args.dtn, inplace=True)
ncontacts = int(seq.seq_len * args.dfactor)
con.sort("raw_score", reverse=True, inplace=True)
con_sliced = con[:ncontacts]

con_matched = con_sliced.match(pdb) 
precision = con_matched.precision
```
to: 
```
con.remove_neighbors(min_distance=args.dtn, inplace=True)
con.sort("raw_score", reverse=True, inplace=True)

con_matched = con.match(pdb, renumber=True, remove_unmatched=True)
precision = con_matched.precision
````
You get coherent scores, in that they are not 1.0.

These score will be same if you run ```conkit_plot peval``` on the two casprr maps. But in this case, your latest commit will return a ```AttributeError``` traceback because ```conkit_plot peval``` is still trying to convert a pdb into contact map.

-------------------------//-----------------------------

I wasn't aware of the Jaccard Index, or any other way to compare the two contact maps. Was trying to make due with what I had...my rationale was this: both ```contact_precision```` and ```conkit_plot peval``` convert a pdb into contact map to compare it with another contact map. So why not just bypass the conversion and compare two contact maps?

The point I was trying to elucidate is why ```conkit_precision``` and ```conkit_plot peval``` calculate things differently when given the same input in casprr format. One appears to makes sense and the other doesn't. But I am aware that both might be wrong since I'm trying to compare two thing that weren't originally meant to be compared this way.

Thanks for the snippet, I will create a script and try to run it on my contact maps.

**Comment by sadiogo** [comment]
Apparently, I wasn't running the latest commit. Tried again and now I receive the following message when trying to compare to contact maps using conkit_precision :
```
usage: conkit_precision.py [-h] [-c PDBCHAIN] [-d DTN] [-f DFACTOR]
                           pdbfile {pdb,mmcif} seqfile seqformat confile
                           conformat
conkit_precision.py: error: argument pdbformat: invalid choice: 'caspmode2' (choose from 'pdb', 'mmcif')
```
I guess you added that to avoid people trying to perform that comparison.

**Comment by FilomenoSanchez** [comment]
Yes I added this change to avoid users trying to calculate precision with a non-PDB file, as it doesn't make sense and it would just throw a `Traceback` error. Anyway regarding what you have observed here, the fact that what you do is remove `con_sliced = con[:ncontacts]` to obtain precision values different than 1.0, what I assume is that the top-L contacts (or whatever L-factor you were using) are the same. I'm not sure why this would be the case if conplot was showing something else, but probably it has to do with the code at `contactmap.match()`. What happens in that function is that if the reference contact map does not have contacts for a given residue, it's considered missing (expected in a PDB) and contacts for this residue are excluded from the calculations. If you were to do this with something other than a PDB it would mess up everything. I would say that's the source of the issue here. I don't think this is a big problem as it works as expected with PDB files. As I mentioned, if you want to compare contact maps, stick to the jaccard index with the script I sent. I'm closing this now as (I think) the question has been answered.

**Comment by sadiogo** [comment]
> I'm closing this now as (I think) the question has been answered.

It has. What you explained about ```contactmap.match()``` makes sense. I'm sticking to the jaccard index. Thanks again!
