### ISSUE TITLE
Images are missing on the documentation website

### ISSUE THREAD

**Issue by tubiana** [rigdenlab/conkit#115]
Hi :) 

I wasn't sure that you were aware that some of the example images are missing in the documentation website :) 
For example: https://www.conkit.org/en/latest/examples/rst/script_plot_scov.html#script-plot-scov

Best regards,
Thibault.

**Comment by FilomenoSanchez** [comment]
Hi @tubiana, thanks for pointing this out!

**Comment by FilomenoSanchez** [comment]
It should be fixed now, you might need to clear the cache of your browser to see the figures. Thanks again!
