### ISSUE TITLE
Error encountered in assign_sequence_register()

### ISSUE THREAD

**Issue by biochunan** [rigdenlab/conkit#27]
#### Input files:
[pdb1ffu_modified.rr.txt](https://github.com/rigdenlab/conkit/files/1077998/pdb1ffu_modified.rr.txt)
[1ffu.fasta.txt](https://github.com/rigdenlab/conkit/files/1078168/1ffu.fasta.txt)

```python
>>> import conkit.io
>>> seq = conkit.io.read("1ffu.fasta.txt", "fasta").top_sequence
>>> conpred = conkit.io.read("pdb1ffu_modified.rr.txt", "casprr").top_map
>>> conpred.sequence = seq
>>> conpred.assign_sequence_register()
```

## Traceback

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/felix/develop/conkit/conkit/core/__init__.py", line 1202, in assign_sequence_register
    c.res2 = self.sequence.seq[res2_index - 1]
IndexError: string index out of range
```

**Comment by fsimkovic** [comment]
The ``seq`` instance contains multiple `Sequence` instances. You can select which `Sequence` to assign to the `ContactMap` by indexing the `SequenceFile` instance. In your case, it appears that chain B in your sequence file is the correct one, so try this:
```python
>>> seq = conkit.io.read("1ffu.fasta.txt", "fasta")[1]
```
or alternatively use the identifier directly
```python
>>> seq = conkit.io.read("1ffu.fasta.txt", "fasta")["1FFU:B|PDBID|CHAIN|SEQUENCE"]
```
