### ISSUE TITLE
PyPi installation missing requirements.txt

### ISSUE THREAD

**Issue by fsimkovic** [rigdenlab/conkit#29]
Bug report via email from Miguel Correa Marrero.

----

## General Information

- ConKit version: 0.7
- Other: PyPi installation

## Example

```
pip install conkit
```

## Traceback

```
Collecting conkit
  Using cached conkit-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pb/v53jszj56fjb8kcsrtdrkwfm0000gn/T/pip-build-Ki0agG/conkit/setup.py", line 105, in <module>
        DEPENDENCIES = dependencies()
      File "/private/var/folders/pb/v53jszj56fjb8kcsrtdrkwfm0000gn/T/pip-build-Ki0agG/conkit/setup.py", line 37, in dependencies
        with open('requirements.txt', 'r') as f_in:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by fsimkovic** [comment]
Fixed in ac5e9e9db112a4a5c8499a0705eb2ed80c1fb806

**Comment by tdiethe** [comment]
Hi guys - came across this with the same issue. I realise you fixed this already but there's a [simpler alternative](https://stackoverflow.com/a/38533721/1038264)

HTH

**Comment by fsimkovic** [comment]
@tdiethe thank you for pointing this out although I think adding a `MANIFEST.in` file purely for the purpose of specifying the installation requirement arguments is great.

Whilst searching for alternatives, I have found a solution that does seem to be quite neat. You can specify all dependencies in `setup.py` and [include a `requirements.txt` only with content "`.`"](https://stackoverflow.com/a/19081268/3046533).
