### ISSUE TITLE
Writing out effective sequences  MSA

### ISSUE THREAD

**Issue by BIORAK** [rigdenlab/conkit#64]
Hi,

   Is there a way to write out the MSA containing only the effective sequences (Neff or Meff) ?

Regards
Rakesh

**Comment by fsimkovic** [comment]
This is not, strictly speaking, possible. In ConKit, Meff/Neff is calculated by weighting each sequence according to its similarity to others in the MSA. In other words, if two sequences are very similar (default ID > 80%), then their contribution to Meff is 0.5 each. Thus, reducing to the alignment to the effective sequences is not possible.

You have two options:

* [Calculate the weights](http://conkit.org/en/0.11.2/api/generated/conkit.core.sequencefile.html#conkit.core.sequencefile.SequenceFile.get_weights) of each sequence, and remove ones below a certain threshold --- *though this will help you with what you'd like to achieve!!*
* [Remove redundant sequences](http://conkit.org/en/0.11.2/api/generated/conkit.core.sequencefile.html#conkit.core.sequencefile.SequenceFile.filter) from your alignment. This is not identical but very similar and usually enough depending on your application --- alternatively you could also use HHfilter either via the ConKit wrapper or the CL application.
