### ISSUE TITLE
can we convert casp rr format to pdb format file?

### ISSUE THREAD

**Issue by kjing** [rigdenlab/conkit#81]
## General Information

I try below command, it seems that pdb writr function doesn't implement yet?

root@e73a6780ab26:/tmp/working/results/protein/1GOU# conkit-convert 1GOU.RR casp new.mmcif mmcif
Convertin file
	1GOU.RR of format casp
to file
	new.mmcif of format mmcif
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conkit/command_line/conkit_convert.py", line 87, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/conkit/command_line/conkit_convert.py", line 77, in main
    conkit.io.convert(args.infile, args.informat, args.outfile, args.outformat)
  File "/opt/conda/lib/python3.7/site-packages/conkit/io/__init__.py", line 86, in convert
    write(fname_out, format_out, hierarchy)
  File "/opt/conda/lib/python3.7/site-packages/conkit/io/__init__.py", line 174, in write
    parser_out.write(f_out, hierarchy, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conkit/io/pdb.py", line 256, in write
    self._write(f_handle, hierarchy)
  File "/opt/conda/lib/python3.7/site-packages/conkit/io/pdb.py", line 206, in _write
    raise NotImplementedError("Write function not available")
NotImplementedError: Write function not available

**Comment by fsimkovic** [comment]
@kjing The CASP format encodes information about which residues in the sequence (2D) are in likely to be close in space (3D). AFAIK, it does not contain information about residue positions in a Cartesian coordinate system (3D), which the PDB format stores. Thus, you can convert PDB (3D) to CASP (2D) but the inverse is not possible without further information.

**Comment by fsimkovic** [comment]
I may add, if you would like to display a contact map in applications such as PyMOL, you may need to use slightly different package. A number of years ago I had good success with [PyMOL-RR](https://github.com/sseemayer/PyMOL-RR).

**Comment by kjing** [comment]
> I may add, if you would like to display a contact map in applications such as PyMOL, you may need to use a slightly different package. A number of years ago I had good success with [PyMOL-RR](https://github.com/sseemayer/PyMOL-RR).

Thanks very much for your prompt response. I try PyMOL-RR in the PyMol 2.4, it doesn't work for some reason.
